### ISSUE TITLE
sidebar

### ISSUE THREAD

**Issue by Zainabfadeyi** [Zainabfadeyi/person-finance-manager#2]
I have created the broiler plates i.e sidebar.js and sidebardata.js  that's the necessary things you need to create a sidebar 
note:

1. I added how you will name your classes i.e. your class name using 
classname={styles. sidebar } as an example and I have imported the CSS file for the sidebar component so add your CSS in there which is sidebar.module.css

2.  I expect you don't even use a day to get it done you are only adding the UI that's all I need you to be quick about it if you need any help feel free to text me on WhatsApp 

3. lastly, create your branch and work in there DO NOT work on the main branch when you are done create a pull request and send it in this issue as a reply and I will close the issue and also send a screenshot attached to the file so I can see how your UI is before merging it to the main branch or make corrections if due

thank you

**Comment by richkazz** [comment]
https://github.com/Zainabfadeyi/person-finance-manager/pull/4
![image](https://github.com/user-attachments/assets/bf3c5179-4b67-49ab-8b3f-c8ca5006f0cb)
![image](https://github.com/user-attachments/assets/73cb0746-30c9-46f8-9620-8e0b6b5d3a35)

**Comment by Zainabfadeyi** [comment]
Good job
